import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/timetable_event.dart';

class TimetablePdfGenerator {
  static Future<void> generateAndPrintPdf(List<TimetableEvent> events) async {
    final pdf = pw.Document();

    // Group events by day
    final Map<String, List<TimetableEvent>> groupedEvents = {};
    for (var event in events) {
      final dayKey = DateFormat('yyyy-MM-dd').format(event.startTime);
      if (!groupedEvents.containsKey(dayKey)) {
        groupedEvents[dayKey] = [];
      }
      groupedEvents[dayKey]!.add(event);
    }

    // Sort days
    final sortedDays = groupedEvents.keys.toList()..sort();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('My Visual Timetable', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(DateFormat('MMMM yyyy').format(DateTime.now()), style: const pw.TextStyle(fontSize: 14)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            if (events.isEmpty)
              pw.Center(child: pw.Text('No events scheduled.', style: const pw.TextStyle(fontSize: 16)))
            else
              ...sortedDays.map((dayStr) {
                final List<TimetableEvent> dayEvents = groupedEvents[dayStr]!;
                dayEvents.sort((a, b) => a.startTime.compareTo(b.startTime));
                final date = DateTime.parse(dayStr);
                
                return pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(DateFormat('EEEE, MMM d').format(date), style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
                    pw.SizedBox(height: 8),
                    pw.Table(
                      border: pw.TableBorder.all(color: PdfColors.grey300),
                      columnWidths: {
                        0: const pw.FlexColumnWidth(1),
                        1: const pw.FlexColumnWidth(3),
                        2: const pw.FlexColumnWidth(2),
                      },
                      children: [
                        // Header
                        pw.TableRow(
                          decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                          children: [
                            pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Time', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                            pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Event / Block', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                            pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Type', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                          ],
                        ),
                        // Rows
                        ...dayEvents.map((TimetableEvent e) {
                          String typeStr = 'Standard';
                          if (e.type == EventType.deepWork) typeStr = 'Deep Work';
                          if (e.type == EventType.adminBuffer) typeStr = 'Admin Buffer';
                          if (e.type == EventType.breakBlock) typeStr = 'Break';

                          return pw.TableRow(
                            children: [
                              pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${DateFormat('HH:mm').format(e.startTime)} - ${DateFormat('HH:mm').format(e.endTime)}')),
                              pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(e.title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                              pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(typeStr)),
                            ],
                          );
                        }),
                      ],
                    ),
                    pw.SizedBox(height: 20),
                  ],
                );
              }),
            pw.SizedBox(height: 20),
            pw.Text('Generated by SwapEat Smarti Platform', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Timetable_${DateFormat('yyyy-MM-dd').format(DateTime.now())}.pdf',
    );
  }
}
