// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzjR8U8AyHYjcPOh0LEq9PmpAOYD0CPuA',
    appId: '1:115680675766:android:e70f55fa384b26baece317',
    messagingSenderId: '115680675766',
    projectId: 'swapeat-39f5e',
    databaseURL: 'https://swapeat-39f5e-default-rtdb.firebaseio.com',
    storageBucket: 'swapeat-39f5e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jdMKQO8D6_VSi5jx-xzbxnuvf633y8c',
    appId: '1:115680675766:ios:baa6548e19675ecfece317',
    messagingSenderId: '115680675766',
    projectId: 'swapeat-39f5e',
    databaseURL: 'https://swapeat-39f5e-default-rtdb.firebaseio.com',
    storageBucket: 'swapeat-39f5e.firebasestorage.app',
    androidClientId: '115680675766-heo9a25vfps5mn863kevfffkqah3l5fo.apps.googleusercontent.com',
    iosClientId: '115680675766-q01nup0okeut9mb292ipm9j4fam9uuh2.apps.googleusercontent.com',
    iosBundleId: 'co.ke.delstarfordworks.dishi',
  );
}
